### ISSUE TITLE
Inkscape produces SVG with exponent notation

### ISSUE THREAD

**Issue by wolfv** [cjlano/svg#4]
Sometimes, Inkscape produces values with exponent notation, such as `0,3e-5 z`.

This could be a fix: http://stackoverflow.com/questions/2293780/how-to-detect-a-floating-point-number-using-a-regular-expression

**Comment by cjlano** [comment]
Hi @wolfv and thank you for your feedback!

Actually, there are a lot of limitations in this SVG Path parser. It should implement the complete [SVG grammar for path data](http://www.w3.org/TR/SVG11/paths.html#PathDataBNF) instead of relying on regular expression parsing.

This is a lot of work, but it could be ease with the use of [pyparsing](http://pyparsing.wikispaces.com/) Python module.

Patches welcome :smile:

**Comment by cjlano** [comment]
Closed by #5 thanks to @lesteve
